trigger: none
variables:
  vmImage: 'ubuntu-latest'
pool:
  name: ubuntu-latest
stages: 
- stage: build
  displayName: build stage
  jobs:
  - job: mavenpackageandpublishartifact
    displayName: build and publish artifact
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: pom.xml
    - task: CopyFiles@2
      displayName: Copy files to artifact staging directory
      inputs:
        SourceFolder: $(System.DefaultWorkingDirectory)
        Contents:  '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      displayName: publish the package to artifact
      inputs:
        ArtifactName: drop
        PathtoPublish: $(Build.ArtifactStagingDirectory)
- stage: deploy
  displayName: deploy to azure app service
  jobs:
    - job: deploy
      displayName: deploy java web app to azure
      pool:
        vmImage: $(vmImage)
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.ArtifactsDirectory)'
