trigger: none
variables:
  vmImage: 'ubuntu-latest'
pool:
  name: ubuntu-latest
stages: 
- stage: build
  displayName: build stage
  jobs:
  - job: mavenpackageandpublishartifact
    displayName: build and publish artifact
    pool:
      vmImage: $(vmImage)
    steps:
    - task: Maven@3
      displayName: Maven package
      inputs:
        mavenPomFile: pom.xml
    - task: PublishBuildArtifacts@1
      displayName: publish the package to artifact
      inputs:
        ArtifactName: drop
        PathtoPublish: $(System.DefaultWorkingDirectory)/**/target/*.?(war|jar)
        TargetPath: $(Build.ArtifactStagingDirectory)
